# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 457)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.check_letters = QtWidgets.QCheckBox(self.centralwidget)
        self.check_letters.setGeometry(QtCore.QRect(120, 170, 144, 17))
        self.check_letters.setObjectName("check_letters")
        self.Button_generate = QtWidgets.QPushButton(self.centralwidget)
        self.Button_generate.setGeometry(QtCore.QRect(140, 270, 75, 23))
        self.Button_generate.setObjectName("Button_generate")
        self.check_number = QtWidgets.QCheckBox(self.centralwidget)
        self.check_number.setGeometry(QtCore.QRect(120, 200, 137, 17))
        self.check_number.setObjectName("check_number")
        self.label_main = QtWidgets.QLabel(self.centralwidget)
        self.label_main.setGeometry(QtCore.QRect(120, 60, 154, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_main.setFont(font)
        self.label_main.setObjectName("label_main")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 100, 96, 13))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.check_letters.setText(_translate("MainWindow", "використовувати число"))
        self.Button_generate.setText(_translate("MainWindow", "сгенерувати"))
        self.check_number.setText(_translate("MainWindow", "використання алфавіт"))
        self.label_main.setText(_translate("MainWindow", "генерація паролів"))
        self.label_2.setText(_translate("MainWindow", "тут буде результа"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
